Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/11/2022
Var
// Seção de Declarações das variáveis 
numero:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para numero de 0 ate 100 passo 2 faça
escreva(numero,"")
fimpara
Fimalgoritmo